# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:23
from __future__ import unicode_literals

import concurrency.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookapp.Book')),
                ('quantity', models.IntegerField()),
                ('version', concurrency.fields.IntegerVersionField(default=1, help_text='record revision number')),
            ],
        ),
    ]
